services:
  postgres:
    image: postgres:15
    container_name: Fin-PostgresDB
    restart: "no"
    env_file:
      - .env
    environment:
      TZ: Europe/Zurich
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_FASTAPI_USER}
      POSTGRES_PASSWORD: ${DB_FASTAPI_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:  # TODO complex healthcheck that tests db/table existence
      test: ["CMD-SHELL", "pg_isready -U ${DB_FASTAPI_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: Fin-fastAPI
    restart: "no"
    environment:
      TZ: Europe/Zurich
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: Fin-Vue
    restart: "no"
    environment:
      TZ: Europe/Zurich
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
